### ISSUE TITLE
Submit a Listing....do we click the edit tab to fill the form for listing

### ISSUE THREAD

**Issue by saturay** [LamTechConsult/searchsierraleone#4]

**Comment by click2tman** [comment]
You start typing the address in the Geocode address field of the business or an address that is close by and known by Google and click on the suggested result that is exactly what you want to type or close to it. If its known by Google, the coordinates will be populated for you below. If its not known, they will need to be entered manually or we will need to enter a close by location instead. At some point, we will need to add the locations to Google map ourselves to ensure they are on the map. After a while, google will learn about them and know their exact location to pre populate the coordinates in the future

**Comment by saturay** [comment]
Thanks
